name-template: 'v$RESOLVED_VERSION ⛵'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
# Disable # and @ mentions, along with code blocks in titles 
change-title-escapes: '\<*_&#@`'
template: |
  ## What’s Changed

  $CHANGES
