name-template: 'v$RESOLVED_VERSION ⛵'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
# Disable certain characters in title from being interpreted as markdown
change-title-escapes: '\<*_&#'
template: |
  ## What’s Changed in $RESOLVED_VERSION

  $CHANGES
